print("^^^^^^^^^^^^^^^^^^")
print("연산 프로그램")
print("^^^^^^^^^^^^^^^^^^")
#a=int(input('첫 번째 값:'))
#b=int(input('두 번째 값:'))
a,b=map(int,input('값을 공백으로 분리해서 차례대로 입력하세요: ').split())
print("^^^^^^^^^^^^^^^^^^")
print(a,'+',b,'=',a+b)
print(f'{a} - {b} = {a-b}')
print(f'{a} * {b} = {a*b}')
print(f'{a} / {b} = {a/b}')
print(f'{a} // {b} = {a//b}')
print(f'{a} % {b} = {a%b}')
print(f'{a} ** {b} = {a**b}')