print("######################")
print('   BMI 계산 프로그램   ')
print("######################")
h=float(input('키: ')); w=float(input('몸무게: '))
print("######################")
bmi=w/((h/100)**2)
print(f'당신의 BMI 지수는 {bmi}입니다.')